apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-backend-server
  template:
    metadata:
      labels:
        app: api-backend-server
    spec:
      containers:
        - name: api-backend-server
          image: prvn347/api:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: api-backend-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: api-backend-server

  type: LoadBalancer
