apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-server
  template:
    metadata:
      labels:
        app: db-server
    spec:
      containers:
        - name: db-server
          image: prvn347/db-server
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-url-secret
                  key: DATABASE_URL
