apiVersion: v1
kind: Secret
metadata:
  name: db-url-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Byb2JvX293bmVyOjNBcFZEenk3Um5vTkBlcC1taXN0eS1zbW9rZS1hNWMwMjVsNi51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9wcm9ibz9zc2xtb2RlPXJlcXVpcmU=
