apiVersion: v1
kind: Service
metadata:
  name: trade-ws-service
spec:
  selector:
    app: trade-ws
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007 # This port can be any valid port within the NodePort range
  type: NodePort
