apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-engine
  template:
    metadata:
      labels:
        app: worker-engine
    spec:
      containers:
        - name: worker-engine
          image: prvn347/worker-engine
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
