apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-ws-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-ws-server
  template:
    metadata:
      labels:
        app: trade-ws-server
    spec:
      containers:
        - name: trade-ws-server
          image: prvn347/trade-ws-server
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: trade-ws-server-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: trade-ws-server
