name: Continuous Deployment
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./trading-server/Dockerfile
          push: true
          tags: prvn347/api:latest

      - name: Build and push engine
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./worker-engine/Dockerfile
          push: true
          tags: prvn347/worker-engine:latest

      - name: Build and push db
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./db-server/Dockerfile
          push: true
          tags: prvn347/db-server:latest

      - name: Build and push ws
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./trade-ws-server/Dockerfile
          push: true
          tags: prvn347/trade-ws-server:latest
